# Hello numpy

In [304]:
# This is my Hello World with numpy
import numpy as np

## Basics

In [305]:
a = np.array([1,2,3], dtype="int16")
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float")
c = np.array([ [[1,2],[3,4]], [[7,8],[9,10]] ], dtype="str")

print(a,b,c,sep="\n\n")

[1 2 3]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[['1' '2']
  ['3' '4']]

 [['7' '8']
  ['9' '10']]]


In [94]:
print(a.ndim, b.ndim, c.ndim)

1 2 3


In [95]:
print(a.shape, b.shape, c.shape)

(3,) (3, 3) (2, 2, 2)


In [96]:
print(a.dtype, b.dtype, c.dtype)

int16 float64 <U2


In [97]:
print(a.itemsize, b.itemsize, c.itemsize)

2 8 8


In [98]:
print(a.nbytes, b.nbytes, c.nbytes)

6 72 64


In [99]:
print(a.size, b.size, c.size)

3 9 8


## Accessing/Modifying

In [100]:
print(c)

[[['1' '2']
  ['3' '4']]

 [['7' '8']
  ['9' '10']]]


In [101]:
c[1,1,0]

'9'

In [102]:
print(c[1,:,:])

[['7' '8']
 ['9' '10']]


In [103]:
print(c[:,1,:])

[['3' '4']
 ['9' '10']]


In [104]:
print(c[:,:,-2])

[['1' '3']
 ['7' '9']]


array([11, 12, 13], dtype=int16)

## Initializing

In [105]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
np.ones((3,4), dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [107]:
np.full((3,4), 999)

array([[999, 999, 999, 999],
       [999, 999, 999, 999],
       [999, 999, 999, 999]])

In [108]:
np.full(c.shape, 999)

array([[[999, 999],
        [999, 999]],

       [[999, 999],
        [999, 999]]])

In [109]:
np.full_like(c, 999) # !!!

array([[['99', '99'],
        ['99', '99']],

       [['99', '99'],
        ['99', '99']]], dtype='<U2')

In [110]:
np.random.rand(3,4)

array([[0.98004579, 0.65645376, 0.29558176, 0.12445946],
       [0.18199695, 0.29069304, 0.05558441, 0.0142586 ],
       [0.16922921, 0.76328367, 0.33238749, 0.21328503]])

In [111]:
np.random.random_sample((3,4))

array([[0.03328751, 0.8682183 , 0.62288775, 0.24198328],
       [0.40829549, 0.7883607 , 0.70774721, 0.71097824],
       [0.78725127, 0.05277943, 0.37554173, 0.8169793 ]])

In [119]:
np.random.randint(7, size=(3,4))

array([[4, 1, 3, 2],
       [0, 4, 3, 3],
       [4, 2, 2, 2]])

In [120]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int16)

In [128]:
np.repeat(c, 3, axis=1)

array([[['1', '2'],
        ['1', '2'],
        ['1', '2'],
        ['3', '4'],
        ['3', '4'],
        ['3', '4']],

       [['7', '8'],
        ['7', '8'],
        ['7', '8'],
        ['9', '10'],
        ['9', '10'],
        ['9', '10']]], dtype='<U2')

In [200]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [201]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [206]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [207]:
np.logspace(1,2,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [135]:
x = np.ones((5,5))
# print(x)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

x[1:-1, 1:-1] = z
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying

In [143]:
d = a.copy()
d[:] = 9, 8, 7
print(a,d)

[1 2 3] [9 8 7]


## Maths

In [163]:
a

array([1, 2, 3], dtype=int16)

In [164]:
a + 100

array([101, 102, 103], dtype=int16)

In [165]:
a - 100

array([-99, -98, -97], dtype=int16)

In [166]:
a * 10

array([10, 20, 30], dtype=int16)

In [167]:
a / 10

array([0.1, 0.2, 0.3])

In [168]:
a // 2

array([0, 1, 1], dtype=int16)

In [169]:
a % 2

array([1, 0, 1], dtype=int16)

In [172]:
a += 10
a -= 10

In [173]:
a + a

array([22, 24, 26], dtype=int16)

In [174]:
np.sin(a)

array([-0.9999902 , -0.53657293,  0.42016703], dtype=float32)

In [175]:
np.tan(a)

array([-225.95085   ,   -0.6358599 ,    0.46302113], dtype=float32)

### Linear Algebra

In [179]:
p = np.ones((2,3))
q = np.full((3,2), 2)
print(p)
print(q)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [182]:
np.matmul(p,q)

array([[6., 6.],
       [6., 6.]])

In [186]:
i = np.identity(5)
np.linalg.det(i)

1.0

In [189]:
np.dot(a,b)

array([150., 186., 222.])

In [190]:
np.inner(a,b)

array([ 74., 182., 290.])

In [193]:
q1 = np.array([0,1])
q2 = np.array([1,0])
np.kron(q1,q2)

array([0, 0, 1, 0])

In [216]:
np.linalg.norm(b)

16.881943016134134

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

## Statistics

In [225]:
s = np.array([[1,2,3], [4,5,6]])

In [231]:
np.min(s, axis=1)

array([1, 4])

In [232]:
np.max(s)

6

In [233]:
np.sum(s)

21

## Reorganizing

In [241]:
h = np.array([[1,2,3,4], [6,7,8,9]])
print(h)
print(h.reshape((4,2)))
print(h.reshape((2,2,2)))

[[1 2 3 4]
 [6 7 8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [246]:
np.vstack([a,a,a])

array([[11, 12, 13],
       [11, 12, 13],
       [11, 12, 13]], dtype=int16)

In [247]:
np.vstack([h,h])

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [1, 2, 3, 4],
       [6, 7, 8, 9]])

In [251]:
np.hstack([a,a,a])

array([11, 12, 13, 11, 12, 13, 11, 12, 13], dtype=int16)

## Misc

In [270]:
f = np.genfromtxt("somedata.txt", delimiter=" ; ", dtype="str")
f

array([['96', '69'],
       ['5', '51'],
       ['1', '68'],
       ['31', '88'],
       ['21', '22'],
       ['15', '26'],
       ['0', '0'],
       ['11', '62'],
       ['32', '8'],
       ['72', '89'],
       ['50', '33'],
       ['6', '2'],
       ['7', '51'],
       ['91', '74'],
       ['10', '60'],
       ['97', '67'],
       ['36', '68'],
       ['73', '98'],
       ['38', '19'],
       ['91', '0'],
       ['63', '45'],
       ['7', '63'],
       ['60', '59'],
       ['57', '91'],
       ['67', '19'],
       ['0', '59']], dtype='<U2')

In [271]:
f = f.astype("int32")
f

array([[96, 69],
       [ 5, 51],
       [ 1, 68],
       [31, 88],
       [21, 22],
       [15, 26],
       [ 0,  0],
       [11, 62],
       [32,  8],
       [72, 89],
       [50, 33],
       [ 6,  2],
       [ 7, 51],
       [91, 74],
       [10, 60],
       [97, 67],
       [36, 68],
       [73, 98],
       [38, 19],
       [91,  0],
       [63, 45],
       [ 7, 63],
       [60, 59],
       [57, 91],
       [67, 19],
       [ 0, 59]])

In [275]:
f % 2 == 1

array([[False,  True],
       [ True,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False,  True],
       [False,  True],
       [False, False],
       [ True,  True],
       [ True, False],
       [False, False],
       [ True,  True],
       [False, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [False,  True]])

In [276]:
f[f % 2 == 1]

array([69,  5, 51,  1, 31, 21, 15, 11, 89, 33,  7, 51, 91, 97, 67, 73, 19,
       91, 63, 45,  7, 63, 59, 57, 91, 67, 19, 59])

In [280]:
f[[0,1]]

array([[96, 69],
       [ 5, 51]])

In [284]:
j = np.array([1,2,3,4,5])
j[[True, False, False, True, True]]

array([1, 4, 5])

In [300]:
np.any(f >= 98, axis=0)

array([False,  True])

In [301]:
np.all(f >= 98, axis=0)

array([False, False])

In [302]:
((f > 50) & (f < 100))

array([[ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True,  True],
       [False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [False,  True]])

In [303]:
(~(f > 50) & (f < 100))

array([[False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [ True,  True],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True,  True],
       [False,  True],
       [False,  True],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [ True, False]])